### ISSUE TITLE
Can't install asyncore-wsgi when using buildout

### ISSUE THREAD

**Issue by idgserpro** [romanvm/asyncore-wsgi#1]
In the Plone world, we use buildout to install packages.

I can't install  asyncore-wsgi 0.0.6: 

```
Unused options for buildout: 'eggs' 'buildout-user' 'zcml' 'effective-user'.
Installing instance.
/home/user/.buildout/eggs/setuptools-26.1.1-py2.7.egg/pkg_resources/__init__.py:188: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
  stacklevel=1,
Getting distribution for 'asyncore-wsgi>=0.0.4'.
error: [Errno 2] No such file or directory: 'Readme.rst'
An error occurred when trying to install asyncore-wsgi 0.0.6. Look above this message for any errors that were output by easy_install.
While:
  Installing instance.
  Getting distribution for 'asyncore-wsgi>=0.0.4'.
Error: Couldn't install: asyncore-wsgi 0.0.6
```

*error: [Errno 2] No such file or directory: 'Readme.rst'* this happens because the distribution file https://files.pythonhosted.org/packages/c1/a1/e459bd71ca46904b27391240d403f072cd45093e7608551a1f42cf5cd6b4/asyncore-wsgi-0.0.6.tar.gz doesn't have `Readme.rst`, but is referenced in https://github.com/romanvm/asyncore-wsgi/blob/95f0b81344de402396d894331aceef2e454e2a3a/setup.py#L13.

Some info:

https://docs.python.org/2/distutils/sourcedist.html#specifying-the-files-to-distribute
https://github.com/mgedmin/check-manifest

I can install it using pip, maybe that's why no one else has opened an issue about it.

**Comment by romanvm** [comment]
I've added a manifest and updated a version in PyPI.

**Comment by idgserpro** [comment]
Indeed, now it's working, release 0.0.9.
